# Generated by Django 5.2.1 on 2025-05-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.BigIntegerField()),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок резюме"),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=150, verbose_name="Фамилия")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "profession",
                    models.CharField(max_length=255, verbose_name="Профессия"),
                ),
                (
                    "qualification_category",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Категория квалификации",
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Опыт работы (в годах)"
                    ),
                ),
                (
                    "work_experience",
                    models.TextField(blank=True, verbose_name="Опыт работы"),
                ),
                ("education", models.TextField(blank=True, verbose_name="Образование")),
                ("skills", models.TextField(blank=True, verbose_name="Навыки")),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
                (
                    "portfolio_link",
                    models.URLField(blank=True, verbose_name="Ссылка на портфолио"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликовано"),
                            ("archived", "Архивировано"),
                        ],
                        default="draft",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="resume_resu_user_id_5f50e7_idx"
                    )
                ],
            },
        ),
    ]
